# Generated by Django 3.2.9 on 2021-12-02 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_images_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='post',
            new_name='project',
        ),
    ]
