# Generated by Django 3.2.9 on 2021-12-02 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='images',
        ),
    ]
