# Generated by Django 3.2.9 on 2021-12-02 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_comment'),
        ('projects', '0009_auto_20211202_0334'),
    ]

    operations = [
    ]
