# Generated by Django 3.2.9 on 2021-12-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_merge_0004_comment_0009_auto_20211202_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ImageField(upload_to='', verbose_name='Project Cover'),
        ),
    ]
