# Generated by Django 3.2.9 on 2021-12-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20211204_0258'),
        ('projects', '0017_merge_20211204_0838'),
    ]

    operations = [
    ]
