# Generated by Django 3.2.9 on 2021-12-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_merge_20211204_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Social', 'Social'), ('Political', 'Political'), ('Sports', 'Sports'), ('Educational', 'Educational')], default='Social', max_length=11),
        ),
    ]
