# Generated by Django 3.2.9 on 2021-12-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avg_rate',
            field=models.FloatField(default=0),
        ),
    ]
