# Generated by Django 3.2.9 on 2021-12-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_avg_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_rates',
            field=models.IntegerField(default=0),
        ),
    ]
