# Generated by Django 3.2.9 on 2021-12-06 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='images',
            new_name='img',
        ),
    ]
